# this is a instruction file for the pytest - > opens main.py and looks for funtion that start wtih test_*** and calls those function automatically


[pytest]
python_files = main.py
addopts = --html=report.html --self-contained-html --alluredir=allure-results --clean-alluredir
markers =
    security: mark a test as a security test case
